# -*- coding: utf-8 -*-

"""
.. module:: prodiguer.db.constants.py
   :platform: Unix
   :synopsis: Prodiguer db constants.

.. moduleauthor:: Mark Conway-Greenslade <momipsl@ipsl.jussieu.fr>


"""
# Constants pertaining to simulation space.
SIMULATION_SPACE_DEVT = 'DEVT'
SIMULATION_SPACE_FAIL = 'FAIL'
SIMULATION_SPACE_PROD = 'PROD'
SIMULATION_SPACE_TEST = 'TEST'

# Constants pertaining to execution states.
EXECUTION_STATE_QUEUED = u"QUEUED"
EXECUTION_STATE_QUEUED_ID = 1
EXECUTION_STATE_RUNNING = u"RUNNING"
EXECUTION_STATE_RUNNING_ID = 2
EXECUTION_STATE_SUSPENDED = u"SUSPENDED"
EXECUTION_STATE_SUSPENDED_ID = 3
EXECUTION_STATE_COMPLETE = u"COMPLETE"
EXECUTION_STATE_COMPLETE_ID = 4
EXECUTION_STATE_ROLLBACK = u"ROLLBACK"
EXECUTION_STATE_ROLLBACK_ID = 5
EXECUTION_STATE_ERROR = u"ERROR"
EXECUTION_STATE_ERROR_ID = 6

# Set of supported execution states.
EXECUTION_STATE_SET = [
    EXECUTION_STATE_QUEUED,
    EXECUTION_STATE_RUNNING,
    EXECUTION_STATE_SUSPENDED,
    EXECUTION_STATE_COMPLETE,
    EXECUTION_STATE_ROLLBACK,
    EXECUTION_STATE_ERROR
]

# Set of supported execution state id's.
EXECUTION_STATE_SET_ID_LIST = [
    EXECUTION_STATE_QUEUED_ID,
    EXECUTION_STATE_RUNNING_ID,
    EXECUTION_STATE_SUSPENDED_ID,
    EXECUTION_STATE_COMPLETE_ID,
    EXECUTION_STATE_ROLLBACK_ID,
    EXECUTION_STATE_ERROR_ID
]

# Set of supported execution state to db id mappings.
EXECUTION_STATE_ID_SET = {
    EXECUTION_STATE_QUEUED : EXECUTION_STATE_QUEUED_ID,
    EXECUTION_STATE_RUNNING : EXECUTION_STATE_RUNNING_ID,
    EXECUTION_STATE_SUSPENDED : EXECUTION_STATE_SUSPENDED_ID,
    EXECUTION_STATE_COMPLETE : EXECUTION_STATE_COMPLETE_ID,
    EXECUTION_STATE_ROLLBACK : EXECUTION_STATE_ROLLBACK_ID,
    EXECUTION_STATE_ERROR : EXECUTION_STATE_ERROR_ID
}
